tags: "solo high_res"
max_threads: 5
image_folder: "downloads"
amount: 50

# Site-specific credentials (overrides defaults)
rule34_api_key: "..."
rule34_user_id: "..."

gelbooru_api_key: "..."
gelbooru_user_id: "..."
